### ISSUE TITLE
I can't run ./configure PYTHON=/usr/bin/python3 configure not found

### ISSUE THREAD

**Issue by mitodeboa** [libguestfs/hivex#15]
Hello
After installing all dependencies when run ./configure PYTHON=/usr/bin/python3 throws configure not found. It seems than ./autogen.sh is not generating configure script

Regards

**Comment by rwmjones** [comment]
What commands did you type, what was the output?

**Comment by mitodeboa** [comment]
Sorry I forgot to install autoconf
