### ISSUE TITLE
Perl make doesn't use same CC compiler

### ISSUE THREAD

**Issue by mohd-akram** [libguestfs/hivex#26]
It seems `Makefile.PL` doesn't use the same `CC` (and `LD`) compiler passed to configure, which can cause a [failure](https://trac.macports.org/ticket/69913) if the flags passed aren't supported.

**Comment by rwmjones** [comment]
I added a possible fix.  It may also require adding `LD="$(CC)"` there too (not LD="$(LD)" as that seems as if it would be wrong).  Let me know if this fixes it or needs a further change.

**Comment by mohd-akram** [comment]
Thanks for adding it. Yes, it does require adding `LD=$(CC)` as well as the linker is called through it.

**Comment by rwmjones** [comment]
Updated, please try commit 85b2c14 too.

**Comment by mohd-akram** [comment]
That works, thanks!

**Comment by rwmjones** [comment]
Cool, thanks for testing!

**Comment by mohd-akram** [comment]
Sorry, noticed one more thing. It should likely also use the `$(PERL)` variable that it gets from configure rather than `perl`. I see that's already being done for Ruby.

**Comment by rwmjones** [comment]
Should be fixed in commit 1254d2a

**Comment by mohd-akram** [comment]
Thanks!
