### ISSUE TITLE
Build requires unused dependency IO::Stringy

### ISSUE THREAD

**Issue by mohd-akram** [libguestfs/hivex#27]
Just another small issue. Autoconf checks for IO::Stringy but it doesn't seem to be used in the code, and AFAICT does not come bundled with the default Perl install. This can cause the Perl build to be skipped despite it being possible.

**Comment by rwmjones** [comment]
I think it's used in the perl tests (`IO::Scalar`):
https://github.com/libguestfs/hivex/blob/85b2c14ebcf952e56801e8c662528be540d8a451/perl/t/550-regedit-export.t#L22
https://github.com/libguestfs/hivex/blob/85b2c14ebcf952e56801e8c662528be540d8a451/perl/t/560-regedit-import.t#L21
https://github.com/libguestfs/hivex/blob/85b2c14ebcf952e56801e8c662528be540d8a451/perl/t/570-regedit-import2.t#L22

**Comment by mohd-akram** [comment]
Ah, apologies, thanks.
