### ISSUE TITLE
node_add_child didn't support utf16

### ISSUE THREAD

**Issue by ww2000e** [libguestfs/hivex#4]
if I use node_add_child write a chinese word , windows regedit will show error  this node .

**Comment by ww2000e** [comment]
![Uploading hivex.jpg…]()

**Comment by libguestfs** [comment]
Please don't use this issue tracker - it is not monitored.  You can send email about the problem to the mailing list: libguestfs <at> redhat.com.  You'll need to include more information about the problem, such as an example of precisely what you're trying to do.
