### ISSUE TITLE
comipled on windows with vc, found one case that cause missing key

### ISSUE THREAD

**Issue by 593749519** [libguestfs/hivex#7]
Here are two registry keys, if we use the lib to create both, the shorter one is missing when opening with windows regedit.exe:

Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\1\CurrentControlSet\Services\VSS\Diag\Lovelace(__?_GLOBALROOT_Device_HarddiskVolume3_)]

[HKEY_LOCAL_MACHINE\SYSTEM\1\CurrentControlSet\Services\VSS\Diag\Lovelace(C:_)]

**Comment by libguestfs** [comment]
Closed and moved to https://bugzilla.redhat.com/show_bug.cgi?id=1648520
